# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: logos

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - binary: logos
    main: .
    ldflags:
      - -s -w
      - -X github.com/senna-lang/logosyncx/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: senna-lang
    name: Logosyncx
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"

brews:
  - name: logos
    repository:
      owner: senna-lang
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/senna-lang/Logosyncx
    description: "Shared AI agent conversation context — stored in git, no external database required."
    license: MIT
    skip_upload: auto
    install: |
      bin.install "logos"
    test: |
      system "#{bin}/logos", "version"
